alias dr='docker'
alias drc='docker-compose'
alias drcb='docker-compose build'
alias drcu='docker-compose up'
alias drcd='docker-compose down'
alias drps='docker ps'
alias drei='docker exec -it'                       # ssh login: docker exec -it <container name or id> /bin/bash
alias drcps='docker-compose ps'
alias drcbnc='docker-compose build --no-cache'
