alias dr='docker'
alias drc='docker-compose'
alias drcb='docker-compose build'
alias drcu='docker-compose up'
alias drcd='docker-compose down'
alias drps='docker ps'
alias drcr='docker-compose run'
alias dre-i='docker exec -it'                       # ssh login: docker exec -it <container name or id> /bin/bash
alias drcps='docker-compose ps'
alias drcb-nc='docker-compose build --no-cache'
alias drcr-r='docker-compose run --rm'               # web-prod python manage.py test report
