## Git Alaises
alias ga='git add'
alias gacm='git add . && git commit -a'
alias gacmm='git add . && git commit -am'
alias gb='git branch'
alias gbl='git blame'                       # Show who changed what & when in a file. eg. gbl <file>
alias gb-a='git branch -a'                  # List all local and remote branches.
alias gb-d='git branch -d'                  # Delete the branch eg. gb-d <branch-name>
alias gb-m='git branch -m'                  # Rename the current branch eg. gb-m <branch-name>
alias gcm='git commit'
alias gcmm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gco-b='git checkout -b'
alias gcl-f='git clean -f'                  # Delete all untracked files.
alias gcl-df='git clean -df'                # Delete all untracked files and directories.
alias gd='git diff'
alias gf='git fetch'
alias gi='git init'
alias gl='git log'
alias gl--o='git log --oneline'             # Show all logs in one line.
alias gl-p='git log -p'                     # show commit history for last N commits with diff eg. gl-p -2
alias gm-n='git merge --no-ff'
alias gps='git push'
alias gpl='git pull'
alias gplo='git pull origin'
alias gpl--r='git pull --rebase'
alias gpl--ro='git pull --rebase origin'
alias gpl--t='git pull --tags'
alias gpso='git push origin'
alias gpso--t='git push origin --tags'
alias grb-c='git rebase --continue'
alias grb-s='git rebase --skip'
alias gre='git remote'
alias greao='git remote add origin'
alias gresH='git reset HEAD'
alias greso='git remote show origin'         # Show remote branches and their mapping to local.
alias gres-uo='git remote set-url origin'
alias gre-v='git remote -v'
alias gs='git status'
alias gst='git stash'
alias gsts='git stash save'                 # Save changes to a stash. eg. gsts <stash-name> && git stash
alias gstl='git stash list'                 # List all stashes.
alias gstp='git stash pop'                  # Apply a stash and delete it from stash list.
alias gt='git tag'                          # List all tags.              
alias gt-a='git tag -a'                     # Add new tag. eg. gt-a <tag-name>
