alias hm='helm'
alias hmc='helm create'
alias hmg='helm get'
alias hmgh='helm get hooks'
alias hmgm='helm get manifest'                      # hmgm <name>
alias hmi--d--d-r='helm install --debug --dry-run'
alias hmi='helm install'                            # hmi <name> <package>
alias hmls='helm ls'
alias hmlt='helm lint'
alias hmp='helm package'
alias hms='helm show'
alias hmsh='helm search hub'
alias hmsr='helm search repo'
alias hmsv='helm show values'
alias hmt='helm teplate'
alias hmts='helm test'
alias hmui='helm uninstall'                          # hmu <name>
alias hmu='helm upgrade'
alias hmv='helm version'
