alias hm='helm'
alias hmc='helm create'
alias hmls='helm ls'
alias hmi='helm install'            # hmi <name> <package>
alias hmu='helm uninstall'          # hmu <name>
alias hmsh='helm search hub'
alias hmsr='helm search repo'
alias hmlt='helm lint'
alias hmsv='helm show values'
alias hmp='helm package'
alias hmgm='helm get manifest'      # hmgm <name>
