alias catrails="cat $utils/bash/alias/bashrc/rails.bash"
alias catpython="cat $utils/bash/alias/bashrc/python.bash"
alias catnpm="cat $utils/bash/alias/bashrc/npm.bash"
alias catgit="cat $utils/bash/alias/bashrc/git.bash"
alias catdocker="cat $utils/bash/alias/bashrc/docker.bash"
alias catelastic="cat $utils/bash/alias/bashrc/elastic.bash"
alias catpostgres="cat $utils/bash/alias/bashrc/postgres.bash"
alias catrvm="cat $utils/bash/alias/bashrc/rvm.bash"
