alias rv='rvm'
alias rvc='rvm current'                  # print current ruby version and name of used gemsets
alias rvgd='rvm gemdir'                  # display path to current gem directory ($GEM_HOME)
alias rvi='rvm install'                  # install ruby interpreter
alias rvu='rvm use'
alias rvuc='rvm use default'
alias rvusys='rvm use system'
alias rvri='rvm reinstall'               # reinstall ruby and run gem pristine on all gems
alias rvrm='rvm remove'                  # remove ruby and downloaded sources
alias rvl='rvm list'                     # show currently installed ruby interpreters
alias rvlk='rvm list known'              # list available interpreters 
alias rvrq='rvm requirements'            # installs dependencies for building ruby
alias rvui='rvm uninstall'               # uninstall ruby, keeping it's sources
alias rvu='rvm use'
alias rvgs='rvm gemset'
alias rvgsc='rvm gemset create'          # eg: rvmgc <app-name>
alias rvgsl='rvm gemset list'
alias rv--r='rvm --rvmrc'                # eg: rvm--rvmrc ruby-2.6.5@ruby_app
