alias launch-elastic-redis-pg="osascript $utils/scripts/launch-elastic-redis-pg.scpt"
alias launch-services="osascript $utils/scripts/launch-services.scpt"
alias start-elastic-search="$services/elasticsearch-7.6.0/bin/elasticsearch"
alias start-mongod="mongod --dbpath ~/data/db"
alias start-pg_ctl="pg_ctl -D /usr/local/var/postgres start"
alias start-redis-server="redis-server"
