source "$utils/bash/alias/bashrc/projects.bash"
source "$utils/bash/alias/bashrc/git.bash"
source "$utils/bash/alias/bashrc/rails.bash"
source "$utils/bash/alias/bashrc/python.bash"
source "$utils/bash/alias/bashrc/npm.bash"
source "$utils/bash/alias/bashrc/docker.bash"
source "$utils/bash/alias/bashrc/help.bash"
