source "$utils/bash/alias/bashrc/projects.bash"
source "$utils/bash/alias/bashrc/git.bash"
source "$utils/bash/alias/bashrc/commands.bash"
source "$utils/bash/alias/bashrc/python-commands.bash"
source "$utils/bash/alias/bashrc/docker.bash"
source "$utils/bash/alias/bashrc/help.bash"
